/******************************************************************************
Program Name: Number Guessing Game
Created Date: 2/22/17
Created By: Andrew Stites
Purpose: To play a fun game 
*******************************************************************************/

#include <iostream>
#include <string>
#include <time.h>
using namespace std;

/******************************************************************************
Function Name: main()
Parameters: None
Return Value: Int
Acknowledgements: Book, Google, a good friend named Bob, and old Java projects 
*******************************************************************************/

//returns the value of 'int'
//main() is the main method
int main() 
{
	//Properly seeds the random function
	//Only use once
	srand(time(0));

	//Used char for a "y/n" conditional statement
	//Used a constant for "ROUND" for the for loop
	//Used two strings for switch statments and output
	char answer;
	const int ROUND = 5; 
	string textMate, counter = "";

	//Used cout object to display the welcome message
	//Used system("pause") to pause the screen for viewing purposes\
	//Used system("cls") to clear the remains of the message
	cout << "Welcome to the number guessing game!!!\n\n";
	system("pause");
	system("cls");

	//Used cout object to display a message to the user
	//Used system("pause") to pause the screen for viewing purposes
	//Used system("cls") to clear the remains of the message
	cout << "All you need to do is guess a number between 1 and 100.\n\n";
	system("pause");
	system("cls");
	
	//Used cout object to display a message to the user
	//Used system("pause") to pause the screen for viewing purposes
	//Used system("cls") to clear the remains of the message
	cout << "You will recieve 5 chances to beat the computer.\n\n";
	system("pause");
	system("cls");
	
	//Used cout object to display a message to the user
	//Used cin object to accept user's answer
	cout << "Do you accept?(y/n): ";
	cin >> answer;

	//Used an if statement for some logic
	if (answer == 'y' || answer == 'Y')
	{
		//The random number generated by rand()
		//Outside of the loop to stay one number the entire time
		int random_Number = rand() % 100 + 1;

		//The do while loop that runs the game
		int round = 5;
		do
		{

			//Used an 'int' variable for user's guess
			//Used cout object to ask question
			//Used cin object to hold value
			int users_Guess = 0;
			cout << "What is your guess?: ";
			cin >> users_Guess;

			//First switch statement for winning statements
			switch (round) {
			case 1: textMate = "Well you got it, but on the last turn!!! Hey, a win is still a win, amirite?"; break;
			case 2: textMate = "You got it on the fourth round!!! You get a nod of acceptance."; break;
			case 3: textMate = "You got it on the third round!!! You get a thumb's up!!"; break;
			case 4: textMate = "You did it on the second try!!! High-five for you!!!"; break;
			case 5: textMate = "Congratulations!!! You got it on the first try!!!"; break;
			}

			//Second switch statement for chances left
			switch (round) {
			case 5: counter = "You have 4 chances left"; break;
			case 4: counter = "You have 3 chances left"; break;
			case 3: counter = "You have 2 chances left"; break;
			case 2: counter = "You have 1 chance left"; break; 
			case 1: counter = ""; break;
			}
			
			//If statement regarding user's guess and random number generated
			if (users_Guess == random_Number)
			{
				//Displays the winning statements
				//Used system("pause") to pause the screen
				//Stops the loop
				cout << textMate << endl;
				system("pause");
				break;
			}
			//Else if statement for more logic
			else if (users_Guess > random_Number && users_Guess <= 100) 
			{
				cout << "Your guess was too high!" << endl << endl;
				round--;
				cout << counter << endl;
				continue;
			}
			else if (users_Guess < random_Number && users_Guess >= 1)
			{
				cout << "Your guess was too low!" << endl << endl;
				round--;
				cout << counter << endl;
				continue;
			}
			//Regarding the input of something other than an integer
			else if (users_Guess < 1 || users_Guess > 100)
			{	
				cout << "Please enter a valid integer that is in the range of 1 to 100" << endl;
				system("pause");
				continue;
			}
		//declares whether the do-while loop goes again	
		}while (round > 0);

			//cancels the game and tells the player the correct answer
			if (round == 0)
			{
				cout << "Sorry, game over!!!" << " The correct answer was " << random_Number << "!" << endl;
				system("pause");
			}
	} 
	//If statement for if 'n' was chosen in the beginning
	else if (answer == 'n' || answer == 'N')
	{
		cout << "You think you  are too good for this game, huh?\n";
		system("pause");
		system("cls");
		cout << "You know what, this game is too good for you!!!\n";
		system("pause");
		system("cls");
		cout << "Go play Minecraft, you scrub!!!\n";
		system("pause");
		system("cls");
	}
	//Else statement regarding putting nothing at the beginnning
	else 
	{
		cout << "What do you think you are doing?!\n";
		system("pause");
		system("cls");
		cout << "We are done here!!!\n";
		system("pause");
		system("cls");
	}
//"This was successful"
return 0;
}